baseURL = 'https://example.org/'
languageCode = 'de-DE'
title = 'Ozan Demir'
theme = 'hugo-coder' 

defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"
noClasses = false

[params]
  author = "Ozan Demir"
  info = "IT-Enthusiast, Datenzauberer"
  description = "Ozan's personal website"
  keywords = "entwickler,persönlich,projekt,it"
  avatarurl = "images/avatar.jpg"
  #gravatar = "ozan.demir@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/wizardOzan"
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://de.linkedin.com/in/ozan-demir-6514211ba"

# Menu links
[languages]
languageName = ":DE:"

[languages.de]
[[languages.de.menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[languages.de.menu.main]]
  name = "Kontakt"
  weight = 2
  url = "about/"
[[languages.de.menu.main]]
  name = "Projekte"
  weight = 3
  url = "projects/"

[languages.en]
languageName = ":uk:"

[languages.en.params]
author = "Ozan"
info = "IT-Enthusiast, Datawizard"
description = "Ozans personalwebsite"
keywords = "blog,develope,it,project"

[[languages.en.menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[languages.en.menu.main]]
  name = "Contact"
  weight = 2
  url = "about/"
[[languages.en.menu.main]] 
  name = "Projects"
  weight = 3
  url = "projects/"